Repository whymath/Melting-Pot-MARL, pull requests merged in 2024-05, with the labels that each got.

#2 Experiment 1 Implementation
  baselines/train/configs.py
  baselines/train/run_ray_train.py
  meltingpot/configs/substrates/__init__.py
  meltingpot/configs/substrates/commons_harvest__private_property.py
  meltingpot/configs/substrates/commons_harvest__private_property_pc.py
Labels: enhancement, experiment

#3 Experiment 6 Implementation
  README.md
  baselines/train/configs.py
  baselines/train/run_ray_train.py
  meltingpot/configs/substrates/__init__.py
  meltingpot/configs/substrates/commons_harvest__open_disable_zapping.py
Labels: enhancement, experiment

#6 Experiment #2 Increasing Apple Regrowth Probs
  .gitignore
  README.md
  baselines/train/configs.py
  baselines/train/run_ray_train.py
  meltingpot/configs/substrates/__init__.py
  meltingpot/configs/substrates/commons_harvest__open_abundance.py
Labels: experiment

#8 Adding dummy script and base observation function for centralized critic implementation
  .gitignore
  baselines/train/centralized_critic_shared_obs.py
  baselines/train/dummy_centralcritic_sharedobs.py
Labels: enhancement

#7 save evaluations groupandfocal in dataset
  baselines/evaluation/evaluate.py
Labels: enhancement

#5 Experiment 3 Implementation
  README.md
  baselines/train/configs.py
  baselines/train/run_ray_train.py
  meltingpot/configs/substrates/__init__.py
  meltingpot/configs/substrates/commons_harvest__farmer.py
  meltingpot/lua/levels/commons_harvest/components.lua
Labels: experiment
